question_data = [
                     {"category": "Science: Computers", "type": "multiple", "difficulty": "easy",
                      "question": "In any programming language, what is the most common way to iterate through an array?",
                      "correct_answer": "&#039;For&#039; loops",
                      "incorrect_answers": ["&#039;If&#039; Statements", "&#039;Do-while&#039; loops",
                                            "&#039;While&#039; loops"]},
                     {"category": "Science: Computers", "type": "multiple", "difficulty": "easy",
                      "question": "What does GHz stand for?",
                      "correct_answer": "Gigahertz", "incorrect_answers": ["Gigahotz", "Gigahetz", "Gigahatz"]},
                     {"category": "Science: Computers", "type": "boolean", "difficulty": "easy",
                      "question": "Linus Torvalds created Linux and Git.", "correct_answer": "True",
                      "incorrect_answers": ["False"]},
                     {"category": "Science: Computers", "type": "multiple", "difficulty": "easy",
                      "question": "If you were to code software in this language you&#039;d only be able to type 0&#039;s and 1&#039;s.",
                      "correct_answer": "Binary", "incorrect_answers": ["JavaScript", "C++", "Python"]},
                     {"category": "Science: Computers", "type": "boolean", "difficulty": "easy",
                      "question": "Pointers were not used in the original C programming language; they were added later on in C++.",
                      "correct_answer": "False", "incorrect_answers": ["True"]},
                     {"category": "Science: Computers", "type": "boolean", "difficulty": "easy",
                      "question": "RAM stands for Random Access Memory.", "correct_answer": "True",
                      "incorrect_answers": ["False"]},
                     {"category": "Science: Computers", "type": "boolean", "difficulty": "easy",
                      "question": "Ada Lovelace is often considered the first computer programmer.",
                      "correct_answer": "True",
                      "incorrect_answers": ["False"]},
                     {"category": "Science: Computers", "type": "boolean", "difficulty": "easy",
                      "question": "In most programming languages, the operator ++ is equivalent to the statement &quot;+= 1&quot;.",
                      "correct_answer": "True", "incorrect_answers": ["False"]},
                     {"category": "Science: Computers", "type": "multiple", "difficulty": "easy",
                      "question": "Which programming language shares its name with an island in Indonesia?",
                      "correct_answer": "Java",
                      "incorrect_answers": ["Python", "C", "Jakarta"]},
                     {"category": "Science: Computers", "type": "multiple", "difficulty": "easy",
                      "question": "In computing, what does LAN stand for?", "correct_answer": "Local Area Network",
                      "incorrect_answers": ["Long Antenna Node", "Light Access Node", "Land Address Navigation"]}]
